config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  mount ActionCable.server => '/cable'

  get '/robots.:format' => 'pages#robots'
  
  namespace :admin do
    root :to => redirect('/admin/orders')

    resources :messages

    resources :orders do
      get 'manage_order' => "orders#manage_order"
      post "update_order_payment_status" => "orders#update_order_payment_status"
      post "update_order_shipment_status" => "orders#update_order_shipment_status"
      post "update_order_payment_remarks" => "orders#update_order_payment_remarks"
      post "update_order_shipment_remarks" => "orders#update_order_shipment_remarks"
      put "remove" => "orders#remove"
    end

    resources :users
    resources :products
    resources :categories, only: [:new, :index, :create, :update, :destroy]
    post "update_ot" => "product_option_types#update"
    post "update_ot_test/:product_id/:option_type_id" => "product_option_types#update_two"
    get  "deleted_index" => "orders#deleted_index"
    get  "deleted_product_index" => "products#deleted_index"
    get  "report"  => 'orders#sales_report'
    get "new_display" => 'settings#new_display'

    resources :products do
      put "remove" => "products#remove"
      put "revive" => "products#revive"
      resources :variants, only: [:show, :edit, :update] do
        resources :images
      end

      resources :images
      get "variant_management" => "variants#manage"
      get "property_management" => "products#manage_properties"
      post "update_variant_status" => "variants#update_active_status" 
      
 
      collection do
        post :update_image_positions
      end

      collection do
        post :update_properties_positions
      end
    end


   

    resources :option_types, only: [:new, :index, :create, :update, :edit] do
      resources :option_values
      collection do
        post :update_options_positions
        post :update_values_positions
      end
    end
  end

  resources :line_items do
    collection do 
      put :update_multiple
    end
  end
  
  root               'static_pages#home'
  get   'home'    => 'static_pages#home'
  get   'refund'  => 'static_pages#refund'
  get   'about'   => 'static_pages#about'
  get   'payment' => 'static_pages#pay_method'
  get   'details' => 'static_pages#about_product'
  get   'contact' => 'static_pages#contact'

  get   'chat'    => 'rooms#show'

  get   'resend_validation'=> 'users#resend_validation'
  post  'resend_va' =>'users#resend_validation_action'
  get   "signup"  => "users#new", :as => "signup"
  post  "signup"  => "users#create"
  get   "order_create"  => "orders#new", :as => "order_create"
  post  "order_create"  => "orders#create"
  get   'login'   => 'sessions#new'
  post  'login'   => 'sessions#create'
  post  'addcart' => 'line_items#create'
  delete'logout'  => 'sessions#destroy'
  get   'store'   => 'store#index'
  get   'checkstock' => 'products#check_stock'
  post  'paypal'  => 'orders#process_paypal'
  get   'password_resets/new'
  get   'password_resets/edit'
  get   'stripe_checkout' => 'stripe_checkouts#stripe_checkout_session'

  mount StripeEvent::Engine, at: '/stripe_hook'
 
  resources :products, only: [:show]
  resources :messages, only: [:new, :create]
  resources :users, only: [:new, :create, :update, :edit]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :store, only: [:index]
  resource  :cart, only: [:index, :show, :destroy]
  resources :orders, only: [:new, :index, :create, :show]
  resource :payment_notification, only: [:create]


end

 









app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @product = Product.select{|x| x.images.count > 0 && x.available? }.last(3).reverse
  end

  def contact
    @message = Message.new(:content => params[:content], :subject => params[:subject], :sender_email => params[:sender_email])
  end

  def about
  end

  def pay_method
  end

  def about_product
  end

  def refund
  end

end

app/views/static_pages/_display_home.html.erb

   
<div class="show_image">
    <% if target.images.any? %>
      <%= link_to image_tag(target.images.first.image_url(:store)), target %>
    <% else %>
      <%= link_to image_tag("img2.png", alt: "Upload Image Here!"), target %>
    <%end%>
</div>


app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="about_page">
	<div class="aboutA">
		<div class="container">
			<div class="col-lg-6 col-md-6 col-xs-12 text1abt1">
				<h1>About Us</h1>
				<p>
					Teesprit (2020) is a brand project to promote local graphic designed tees produced and printed in Malaysia. the tee art print themes are not limited to any, hence the name of the project. We hope these tee arts brings additional variation to the local apparel industry.
					</br>
					</br>
					Tee art-prints here are guaranteed 100% original idea and plagiarism-free. All ideas from puns to local cultures are welcomed. 
					</br>
					</br>
					If you are aspire to share the same idea, collaboration or anything in your mind on this, drop a message <span style="text-decoration: underline; font-weight: bold;"><%= link_to 'here!', contact_path %></span>
					</br>
					</br>
					<!--<i style="color: #1e98b2;" class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp; Artist (photoshop, illustrator)
					</br>
					<i style="color: #1e98b2;" class="fa fa-desktop" aria-hidden="true"></i>&nbsp; Front-end developer (CSS, HTML, Javascript)-->
				</p>
			</div>
			<div class="col-lg-6 col-md-6 col-xs-12 text2abt1">
				<%= image_tag("about1.png", alt: "tee tees tea", class: 'image_abt1') %>
			</div>
		</div>
	</div>

	<div class="aboutB">
		<div class="container">
			<div class="col-lg-6 col-md-6 col-xs-12 text1abt2">
				<%= image_tag("comp.png", alt: "tee tees tea", class: 'image_abt2') %>
			</div>
			<div class="col-lg-6 text2abt2">
				<h1> Service Limitation</h1>
					Currently we are having some limitation with our e-commerce services. We are continuously improving our services to ensure your experience browsing our sites and liaising with us. Sincere apologize for any inconvenience caused! 
					</br>
					</br>
					Current limitations include: 
					</br>
					<p>
					<p>
					<i style="color: #1e98b2; font-size: 1.2em;" class="fa fa-credit-card" aria-hidden="true"></i> &nbsp; Limited payment method (only manual bank-in and Cash on Delivery) <%= link_to 'click here for more info!', payment_path, style: 'font-weight:bold; text-decoration:underline;' %>
					
					</p>

					<p>
					<i style="color: #1e98b2; font-size: 1.2em;" class="fa fa-picture-o fa-2x" aria-hidden="true"></i> &nbsp; <span >Very basic webpage interface. Improvements are underway. Inconvenience caused are deeply regretted. Drop us a message <span style="text-decoration: underline; font-weight: bold;"><%= link_to 'here', contact_path %></span> if you have any suggestions for improvements.
					</span> 
					</p>
					</p>
			</div>
		</div>
	</div>

	<div class="aboutC">
		<div class="container">
			<div class="col-lg-6 col-md-6 col-xs-12 text1abt3">
				<h1>FAQ</h1>
				<p>
					<div style="font-weight: bold; text-decoration: underline;">Purchases outside Malaysia</div>
					Currently this store is only serving local Malaysia market. For outside Malaysia interested purchases, please drop a message <span style="text-decoration: underline; color:  #cb4335"><%= link_to 'here!', contact_path %></span> or visit <span style="text-decoration: underline; color:  #cb4335 ;"><%= link_to 'Society6 shop', "https://society6.com/theeverythingapparel/s?q=popular+apparel" %></span> and <span style="text-decoration: underline; color:  #cb4335 ;"><%= link_to 'Threadless Artist Shop', "https://theeveythingapparel.threadless.com/" %></span> here.			</br>
					</br>
					<div style="font-weight: bold; text-decoration: underline;">Transaction Currency in this store</div>
					MYR (Ringgit Malaysia only)
					</br>
					</br>
					<div style="font-weight: bold; text-decoration: underline;">Item Delivery</div>
					Please allow up to 7 days for delivery arrival to customer doorstep. As this is just started, we might face limitations, apologize for the inconveniences in advanced!
					</br>
					</br>
					<div style="font-weight: bold; text-decoration: underline;">Item Return</div>
					7 days return policy with reasons including tee size, print quality, damaged tees upon arrival and other subjective issues. All in all will open communication to customers to assist on this. 
					</br>
					</br>
					<div style="font-weight: bold; text-decoration: underline;">Nationwide coverage and Transaction Method</div>
					Postage fees applies accordingly in the website. Postage upon Bank-in by customers and COD (Cash on Deliveries) only applies to Klang Valley area.
					<br>
					Delivery fees applies as followed:
					<br>
					<span style="font-weight: bold">RM10.00 </span> - Outside Klang Valley within Peninsula
					<br>
					<span style="font-weight: bold">Free </span> - Klang Valley
					<br>
					<span style="font-weight: bold">RM12.00 </span> - East Malaysia
					<br>
					<br>
					<div style="font-weight: bold; text-decoration: underline;">Caring your Tee</div>
					We advice caring tips for your tee as below:
					<br>
					1. Turn inside out before throwing them into washing machine.
					<br>
					2. Wash similar clothes together. (Clothes with buttons such as jeans or jacket might causes prints to peel)
					<br>
					3. Wash with cold water. (prevent print distillation and save energy too!)
					<br>
					4. Avoid bleach. (strong detergents too as they can dissolve the print coating.)
					<br>
					5. Try drying them under shade. 
					<br>
					6. Iron inside out. (turn garment inside out before ironing, as direct heat on print will affect the color etc.)
					<br>
					<br>
				</p>
			</div>
			<div class="col-lg-6 col-md-6 col-xs-12 text2abt3">
				<%= image_tag("about3.png", alt: "tee tees tea", class: 'image_abt3') %>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/about_product.html.erb
<% provide(:title, Product) %>

<div>

<div class="chart container">
<h1>Tee Size Chart</h1>

<span class="chart_table col-lg-7 col-md-7 col-sm-7 col-xs-12">
<table class="table men_size_table">
  <thead style="background-color: #353535; color: #fff;" >
    <tr>
      <th class="th_chart">Men's Size</th>
      <th>Shoulder</th>
      <th>Chest</th>
      <th>Short Sleeve Length</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">S</th>
      <td>16"</td>
      <td>38"</td>
      <td>7"</td>
      <td>26"</td>
    </tr>
    <tr>
      <th scope="row">M</th>
      <td>17"</td>
      <td>40"</td>
      <td>7.5"</td>
      <td>27"</td>
    </tr>
    <tr>
      <th scope="row">L</th>
      <td>18"</td>
      <td>42"</td>
      <td>8"</td>
      <td>28"</td>
    </tr>
  </tbody>
</table>


<table class="table women_size_table">
  <thead style="background-color: #353535; color: #fff;" >
    <tr>
      <th class="th_chart">Women's Size</th>
      <th>Shoulder</th>
      <th>Chest</th>
      <th>Short Sleeve Length</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">S</th>
      <td>13"</td>
      <td>32"</td>
      <td>6"</td>
      <td>23"</td>
    </tr>
    <tr>
      <th scope="row">M</th>
      <td>14"</td>
      <td>34"</td>
      <td>6.5"</td>
      <td>24"</td>
    </tr>
    <tr>
      <th scope="row">S</th>
      <td>15"</td>
      <td>36"</td>
      <td>6.5"</td>
      <td>25"</td>
    </tr>
  </tbody>
</table>
</span>
<span class="chart_image col-lg-5 col-md-5 col-sm-5 col-xs-12">
<%= image_tag("chart.png", alt: "tee size chart")%>
</span>

</div>

<!-- testing VueJS framework -->

<div style="background-color: #edda82; padding: 15px;">

<% if current_user && current_user.admin? %>
<div id='content' v-cloak>
  <p> {{ title }} </p>
  <p> {{ subtitle('Teesprit') }} </p>
  <p> Watch some videos here in our <a :href="url">Youtube</a> channel. </p> <!-- ":href" short for "v-bind:href" -->
  <input type="text" :value="area" @keyup="updateArea"> 
  <input type="text" v-model="postcode">
  <p> {{ quantity}} (with v-model two way data binding) </p>
  <button v-on:click="quantity++">add quantity</button>
  <button v-on:click="quantity--">reduce quantity</button>

  <p> {{ count }} </p>
  <button v-on:click="changeCount(1)">add count by 1 (single click)</button>
  <button v-on:click="changeCount(-1)">reduce count by 1 (single click)</button>
  <button @dblclick="changeCount(2)">add count by 2 (double click)</button>
  <button @dblclick="changeCount(-2)">reduce count by 2 (double click)</button> <!-- "@" is short for "v:on" -->

  <div class="canvas" style="width: 200px; height: 200px; margin-top: 20px; background-color: #ddd;" @click="logEvent" @mousemove="logCoords">{{coords.x}}, {{coords.y}}</div>

  <p v-if="betul"> I am correct </p>
  <p v-if="salah"> I am wrong, sorry. </p>

<keep-alive>
  <div id="componentA"></div>
</keep-alive>

  <ul>
    <li v-for="(item, index) in items"> {{index+1}}. {{item}} </li>
  </ul>

</div>

<% else %>

<% end %>

</div>

<!-- testing VueJS framework -->


<div class="build">
	<div class="container">
		<p>Comfort & Quality</p>
		<p class="build_des">Our tees are 100% made from cotton, ensuring all day comfort. Art prints are 100% infused into the tees with high quality ink print. The tees measurement are of best fit wear with appropriate proportion. Multiple size and cutting are available. Feel free to contact us <span style="text-decoration: underline; font-weight: bold;"><%= link_to 'here!', contact_path %></span> shall you have additional requirement. Free Delivery in Klang Valley area and 7 days no question free return policy.</p>
	</div>
</div>

<!-- <div class="idea">
	<div class="container">
		<p>How about a special gift to others?<br>
		Contact us for a custom printed card and we will deliver it to your desired recipient.
		Hassle free gesture!</p>
	</div>
</div-->

</div>

<style type="text/css">
  
[v-cloak] > * { visibility: hidden; }
[v-cloak]::before { content: "loading…" }

</style>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<div class="container contact_page">
<div class=" col-lg-4 col-lg-offset-4">
<h1>Contact</h1>
<p>
	Need Assistance? </br>
	Found a bug in our website? </br>
	Problem with orders?</br>
    Returning item?</br>
	Let us know! </br>
	We will get back to you shortly!</br>

	
    <%= form_for @message, :method => :POST do |f| %>
    <%= render "shared/error_messages", :target => @message %>

    <%= f.label :sender_email, 'Email' %><br>
    <%= f.text_field :sender_email, class: 'form-control' %>

    <%= f.label :subject %><br>
    <%= f.text_field :subject, class: 'form-control' %>

    <%= f.label :content %><br>
    <%= f.text_area :content, rows: 3, class: 'form-control' %>


    <% if current_user.nil? %>
    <%= f.hidden_field :user_id, :value => "0" %>
    
    <% else %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <% end %>

          </br>  
    <%= f.submit 'Send Message', class: 'help_submit_button' %>

<% end %>


</p>
</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>


<div class="home">
  <div class="image_switch">
    <div id="carousel-change" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-change" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-change" data-slide-to="1"></li>
        <li data-target="#carousel-change" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active item_1">
          <a href="#"></a>
          <div class="carousel-caption d1">
          <h1><span class="des11">Graphic Tees </span></h1>
          <span class="des12"> A simple Malaysia store, to sell local graphic printed tee with custom drawn arts.  </span>
          <span class="des13"> <%= link_to "Store", store_path, class: 'btn h-btn' %></span>
          </div>
        </div>

        <div class="item item_2">
          <a href="#"></a>
          <div class="carousel-caption d1">
          <span class="des11"> About Our Store </span><br>
          <span class="des12"> Teesprit aims to produce locally designed graphic tee, and spread inspirations. </span>
          <span class="des13"> <%= link_to "About Us", about_path, class: 'btn btn-success' %></span>
          </div>
        </div>

        <div class="item item_3">
          <a href="#"></a>
          <div class="carousel-caption d1">
          <span class="des11"> Free Delivery </span><br>
          <span class="des12"> Free delivery in Klang Valley and 7 days no question return. Terms and conditions applied. </span>
          <span class="des13"> <%= link_to "Details", refund_path, class: 'btn h-btn' %></span>
          </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-change" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-change" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div> <!-- Carousel -->
  </div>


  <div class="new_release container" style="text-align: center;">
      
        <% @product.each do | product | %>  
        <div style=" display: inline-block; margin: 20px;" %>
          <%= react_component("fe/home/ImageCard", {image: product.images.first.image_url, title: product.title, description: truncate(product.description, length: 100), id: product.number}) %>
         </div>
        <% end %>
     

  </div>


<div class="container product_exp">
  <div class="col-lg-5 col-md-10 exp_text">
    <p> 
     <span style="font-weight: bold;">Teesprit</span> aims to produce locally designed graphic tee, and spread inspirations. Be different when wearing our tees. Follow us through social medias to keep updated on our progresses. We hope to spark like minded creative people and inspire all in our journey, as well as adding a little variation into the local apparel line. "Inspire Something"
     <br>
     <br>
     <%= link_to "To Store", store_path, class: 'btn btn-success' %>
    </p>
  </div>
</div>
 
<div class="container guide">
  <div class="col-lg-4 col-xs-12">
    <%= image_tag("reg.png", alt: "local graphic tee") %>
    <p>Register as user to purchase and track order in this page. Alternatively browse and purchase as guest user without registration and track order through email.</p>
  </div>

  <div class="col-lg-4 col-xs-12">
    <%= image_tag("pur.png", alt: "local graphic tee") %>
    <p>Browse through selections in store, with various size and both gender cutting available. Only 5 units available for each design/print variant.</p>
  </div>

  <div class="col-lg-4 col-xs-12">
    <%= image_tag("disti.png", alt: "local graphic tee") %>
    <p>Checkout with two methods, COD (available in Klang Valley only) and Bank-in delivery. <%= link_to 'Click here', payment_path, style: 'font-weight:bold; text-decoration:underline; color: #ff8c00;' %> for more details on payment method. Free delivery in Klang Valley area and 7 days no question return. <%= link_to 'More details here.', refund_path, style: 'font-weight:bold; text-decoration:underline; color: #ff8c00;' %></p>
  </div>
</div>


<div class="container home_link">
  <div class="col-lg-3 col-xs-6" style="position: relative; display: inline-block;">
    <a class="home_button fblink" href="https://www.facebook.com/The-Everything-Apparel-545747722426741/"><span class="blue">Facebook</span></a>
  </div>
  <div class="col-lg-3 col-xs-6" style="position: relative; display: inline-block;">
    <a class="home_button iglink" href="https://www.instagram.com/teesprit.my/?hl=en"><span class="red">Instagram</span></a>
  </div>
  <div class="col-lg-3 col-xs-6" style="position: relative; display: inline-block;">
    <a class="home_button taslink" href="https://theeveythingapparel.threadless.com"><span class="orange">Threadless Artist Shop</span></a>
  </div>
  <div class="col-lg-3 col-xs-6" style="position: relative; display: inline-block;">
    <a class="home_button s6link" href="https://society6.com/teesprit/s?q=popular+apparel"><span class="purple">Society6 Shop</span></a>
  </div>
</div>



  <script type="text/javascript">
  var windowWidth = $(document).width();
  var os = $('.image_switch').offset().top;
  var h = 200;
  var $w = $(window).scroll(function() {


      if($w.scrollTop() > os +  h){
        $('.head.home_header').removeClass('home_header');
        $('.head').addClass('header');  
        $('a.login_button').removeClass('ghost-button-transition'); 
      }
      else {   
        $('.head.header').removeClass('header');
        $('.head').addClass('home_header'); 
        $('a.login_button').addClass('ghost-button-transition');
      }
    
  });
  </script>
  </div>





app/views/static_pages/pay_method.html.erb
<% provide(:title, "Payment") %>
<div class="payment_method">

	<div class="cod col-lg-12">
	<h1 style="margin: 0px;"><p class="titlecod"> Cash On Delivery (COD) </p></h1><br/>
		<div class="col-lg-4 creamy">
			<%= image_tag("cod11.png", alt: "COD", class: "codcon") %>
			<span class="cod1des"> Select Cash On Delivery (COD) as payment option. Note that COD are only available within Klang Valley area.</span>
		</div>

		<div class="col-lg-4 creamy">
			<%= image_tag("cod12.png", alt: "COD", class: "codcon") %>
			<span class="cod1des"> We will Whatsapp and email you to communicate COD location. COD location are as followed or within Klang Valley: </br>
			<i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp;<a href="https://www.google.com/maps/dir/''/Publika+Shopping+Gallery,+1,+Jalan+Dutamas+1,+Solaris+Dutamas,+50480+Kuala+Lumpur,+Federal+Territory+of+Kuala+Lumpur/data=!4m5!4m4!1m0!1m2!1m1!1s0x31cc485e0e965a21:0xd5fc2d7f9da12334?sa=X&ved=0ahUKEwj7u87qxozZAhVEMY8KHTyaBEQQiBMITjAA">Publika</a></br>
			<i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp;<a href="https://www.google.com/maps/dir/''/mytown+cheras/data=!4m5!4m4!1m0!1m2!1m1!1s0x31cc363dccb07b07:0x959c26a50325031d?sa=X&ved=0ahUKEwjYkJ-ix4zZAhUHPI8KHRCsD0oQ9RcIkAEwEA">MyTown, Cheras</a></br>
			<i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp;<span style="font-style: italic;">Other KV Area</span>
			</span>
		</div>


		<div class="col-lg-4 creamy">
			<%= image_tag("cod13.png", alt: "COD", class: "codcon") %>
			<span class="cod1des"> Meet at designated location. Inspection by buyer and cash transaction once buyer satisfied with the product. Further assistance needed please contact us from <%= link_to "here!", contact_path %> Comes with 7 days no question return (with full amount).
			</span>
		</div>

	</div>


	<div class="bi col-lg-12">
	<h1 style="margin: 0px;"><p class="titlebi"> Bank-in (Delivery)</p></h1><br/>
		<div class="col-lg-4 creamy">
			<%= image_tag("cod11.png", alt: "delivery", class: "bicon") %>
			<span class="bi1des"> Select bank-in as payment option. Delivery available nationwide with following rate: </br>
			<i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp; Northen region - RM10</br>
			<i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp; Southern region - RM10</br>
			<i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp; Klang Valley - Free</br>
			<i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp; West Malaysia - RM12 
			</span>
		</div>

		<div class="col-lg-4 creamy">
			<%= image_tag("cod12.png", alt: "COD", class: "bicon") %>
			<span class="bi1des"> We will Whatsapp and email you bank-in details. Pease insert <span style="font-weight: bold;">order number </span> as reference and you may inform us once transaction is done.
			</span>
		</div>


		<div class="col-lg-4 creamy">
			<%= image_tag("bi13.png", alt: "COD", class: "bicon") %>
			<span class="bi1des"> Once payment is confirmed, item will be shipped out to buyer's designated address. Return/refund or any further assistance needed please contact us from <%= link_to "here!", contact_path %> Free Delivery in Klang Valley area with 7 days no question return (refund value exclude delivery fees).
			</span>
		</div>

	</div>

</div>

app/views/static_pages/refund.html.erb
<% provide(:title, "Refund") %>

	<div class="refund_page col-lg-12 container">
	<div class="col-lg-8 col-lg-offset-2">
	<h1> Refund Procedure </h1>

	<p> We accept return and refund for our product. Reach us through the following method: <br>
		<ol type:"1">
		<li>Via Whatsapp (number provided when confirming order)</li>
		<li>Via Email (replying our order email to request item return and refund)</li>
		<li>Via help page, <%= link_to 'Click here!', payment_path, style: 'font-weight:bold; text-decoration:underline; color: #ff8c00;' %></li>
		</ol><br>
		Once we are in touch, we will arrange a refund method at buyer's convenience: <br>
		<ol type:"1">
		<li>Pickup from delivery address or specific location (within Klang Valley area).</li>
		<li>Postage to specific address for buyers from outside Klang Valley. </li>
		</ol>
	</p>

	<h1> Refund Policy </h1>

	<p> We accept return and refund with following policy: <br>
		<ol type:"1">
		<li>7 days from item received, we appreciate feedback on refund reason and nothing more.</li>
		<li>Item must be returned in plastic packaging and in original state. </li>
		<li>Item will be checked with appreciation without any stains etc. </li>
		<li>Please allow 14 days for full refund through bank-in.</li>
		<li>Refund value for delivery include total delivery fees. </li>
		<li>Return postage cost to be beared by buyer.</li>
		<li>We reserved rights for any final decision, at just and fairness to our customers.</li>
		</ol>
		We apologise on the tedious return procedure as we have limited resources currently.
	</p>

	</div>	



</div>