config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  mount ActionCable.server => '/cable'

  get '/robots.:format' => 'pages#robots'
  
  namespace :admin do
    root :to => redirect('/admin/orders')

    resources :messages

    resources :orders do
      get 'manage_order' => "orders#manage_order"
      post "update_order_payment_status" => "orders#update_order_payment_status"
      post "update_order_shipment_status" => "orders#update_order_shipment_status"
      post "update_order_payment_remarks" => "orders#update_order_payment_remarks"
      post "update_order_shipment_remarks" => "orders#update_order_shipment_remarks"
      put "remove" => "orders#remove"
    end

    resources :users
    resources :products
    resources :categories, only: [:new, :index, :create, :update, :destroy]
    post "update_ot" => "product_option_types#update"
    post "update_ot_test/:product_id/:option_type_id" => "product_option_types#update_two"
    get  "deleted_index" => "orders#deleted_index"
    get  "deleted_product_index" => "products#deleted_index"
    get  "report"  => 'orders#sales_report'
    get "new_display" => 'settings#new_display'

    resources :products do
      put "remove" => "products#remove"
      put "revive" => "products#revive"
      resources :variants, only: [:show, :edit, :update] do
        resources :images
      end

      resources :images
      get "variant_management" => "variants#manage"
      get "property_management" => "products#manage_properties"
      post "update_variant_status" => "variants#update_active_status" 
      
 
      collection do
        post :update_image_positions
      end

      collection do
        post :update_properties_positions
      end
    end


   

    resources :option_types, only: [:new, :index, :create, :update, :edit] do
      resources :option_values
      collection do
        post :update_options_positions
        post :update_values_positions
      end
    end
  end

  resources :line_items do
    collection do 
      put :update_multiple
    end
  end
  
  root               'static_pages#home'
  get   'home'    => 'static_pages#home'
  get   'refund'  => 'static_pages#refund'
  get   'about'   => 'static_pages#about'
  get   'payment' => 'static_pages#pay_method'
  get   'details' => 'static_pages#about_product'
  get   'contact' => 'static_pages#contact'

  get   'chat'    => 'rooms#show'

  get   'resend_validation'=> 'users#resend_validation'
  post  'resend_va' =>'users#resend_validation_action'
  get   "signup"  => "users#new", :as => "signup"
  post  "signup"  => "users#create"
  get   "order_create"  => "orders#new", :as => "order_create"
  post  "order_create"  => "orders#create"
  get   'login'   => 'sessions#new'
  post  'login'   => 'sessions#create'
  post  'addcart' => 'line_items#create'
  delete'logout'  => 'sessions#destroy'
  get   'store'   => 'store#index'
  get   'checkstock' => 'products#check_stock'
  post  'paypal'  => 'orders#process_paypal'
  get   'password_resets/new'
  get   'password_resets/edit'
  get   'stripe_checkout' => 'stripe_checkouts#stripe_checkout_session'

  mount StripeEvent::Engine, at: '/stripe_hook'
 
  resources :products, only: [:show]
  resources :messages, only: [:new, :create]
  resources :users, only: [:new, :create, :update, :edit]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :store, only: [:index]
  resource  :cart, only: [:index, :show, :destroy]
  resources :orders, only: [:new, :index, :create, :show]
  resource :payment_notification, only: [:create]


end

 









app/views/layouts/admin/_header.html.erb


<div class="admin-nav">

	<div class="admin-nav-button">
			<span class="menu-toggle"><i class="fa fa-bars"></i></span>
	</div>

	<div class="admin-nav-title">
		<%= link_to "Administration Site", admin_orders_path %>
	</div>

	<div class="admin-user" style="float: right; margin-right:15px;">
		<span style="margin-right: 10px;"> Hi, <%=current_user.name %>! </span>
		<span> <%= link_to "Go To Store", root_path, class: "btn h-btn", style: "margin-bottom: 5px;" %></span>
	</div>

</div>

<div id="wrapper">
	<nav class="navbar sidebar" role="navigation">
		<div id="sidebar-wrapper">
			<ul class="sidebar-nav nav-stacked">
				<li data-toggle="collapse" data-target="#dash" class="collapsed">
					<a href="#" class="prevent disable_link"><i class="fa fa-shopping-cart"></i>ORDER<span class="toggle-icon fa fa-angle-left fa-pull-right"></span></a>
					<ul class="sub-menu collapse option-back" id="dash">
						<li><%= link_to "Order List", admin_orders_path %></li>
						<li><%= link_to "New Order", admin_orders_path %></li>
						<li><%= link_to "Deleted Orders", admin_deleted_index_path, :method => :get %></li>
					</ul>
				</li>
				
				<li data-toggle="collapse" data-target="#products" class="collapsed">
					<a href="#" class="prevent disable_link"><i class="fa fa-file"></i>PRODUCTS<span class="toggle-icon fa fa-angle-left fa-pull-right"></span></a>
					<ul class="sub-menu collapse option-back" id="products">
						<li><%= link_to "Product List", admin_products_path %></li>
						<li><%= link_to "New Product", new_admin_product_path %></li>
						<li><%= link_to "Deleted Products", admin_deleted_product_index_path, :method => :get %></li>
						<li><%= link_to "Manage Option Types", admin_option_types_path %></li>
					</ul>
				</li>

				<li data-toggle="collapse" data-target="#users" class="collapsed">
					<a href="#" class="prevent disable_link"><i class="fa fa-user"></i>USERS<span class="toggle-icon fa fa-angle-left fa-pull-right"></span></a>
					<ul class="sub-menu collapse option-back" id="users">
						<li><%= link_to "User List", admin_users_path %></li>
						<li><%= link_to "New User", new_admin_product_path %></li>
					</ul>
				</li>


				<li data-toggle="collapse" data-target="#messages" class="collapsed">
					<a href="#" class="prevent disable_link"><i class="fa fa-inbox"></i>MESSAGES<span class="toggle-icon fa fa-angle-left fa-pull-right"></span></a>
					<ul class="sub-menu collapse option-back" id="messages">
						<li><%= link_to "Messages", admin_messages_path %></li>
					</ul>
				</li>

				<li data-toggle="collapse" data-target="#report" class="collapsed">
					<a href="#" class="prevent disable_link"><i class="fa fa-usd"></i>SALES REPORT<span class="toggle-icon fa fa-angle-left fa-pull-right"></span></a>
					<ul class="sub-menu collapse option-back" id="report">
						<li><%= link_to "Report", admin_report_path %></li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html lang="en">

	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<meta name="turbolinks-cache-control" content="no-cache">
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= javascript_pack_tag 'application' %>
		<%= favicon_link_tag asset_path('teelogo.png') %>
		<%= render 'layouts/shim' %>
	</head>

	<body class="admin <%= controller_name %> <%= action_name %>">
		<%= render 'layouts/admin/header' %>
	    <div id="page-content-wrapper">
	    	<% flash.each do |message_type, message| %>
				<div class="alert alert-<%= message_type %>" id="flash"><%= message %></div>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>