config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  mount ActionCable.server => '/cable'

  get '/robots.:format' => 'pages#robots'
  
  namespace :admin do
    root :to => redirect('/admin/orders')

    resources :messages

    resources :orders do
      get 'manage_order' => "orders#manage_order"
      post "update_order_payment_status" => "orders#update_order_payment_status"
      post "update_order_shipment_status" => "orders#update_order_shipment_status"
      post "update_order_payment_remarks" => "orders#update_order_payment_remarks"
      post "update_order_shipment_remarks" => "orders#update_order_shipment_remarks"
      put "remove" => "orders#remove"
    end

    resources :users
    resources :products
    resources :categories, only: [:new, :index, :create, :update, :destroy]
    post "update_ot" => "product_option_types#update"
    post "update_ot_test/:product_id/:option_type_id" => "product_option_types#update_two"
    get  "deleted_index" => "orders#deleted_index"
    get  "deleted_product_index" => "products#deleted_index"
    get  "report"  => 'orders#sales_report'
    get "new_display" => 'settings#new_display'

    resources :products do
      put "remove" => "products#remove"
      put "revive" => "products#revive"
      resources :variants, only: [:show, :edit, :update] do
        resources :images
      end

      resources :images
      get "variant_management" => "variants#manage"
      get "property_management" => "products#manage_properties"
      post "update_variant_status" => "variants#update_active_status" 
      
 
      collection do
        post :update_image_positions
      end

      collection do
        post :update_properties_positions
      end
    end


   

    resources :option_types, only: [:new, :index, :create, :update, :edit] do
      resources :option_values
      collection do
        post :update_options_positions
        post :update_values_positions
      end
    end
  end

  resources :line_items do
    collection do 
      put :update_multiple
    end
  end
  
  root               'static_pages#home'
  get   'home'    => 'static_pages#home'
  get   'refund'  => 'static_pages#refund'
  get   'about'   => 'static_pages#about'
  get   'payment' => 'static_pages#pay_method'
  get   'details' => 'static_pages#about_product'
  get   'contact' => 'static_pages#contact'

  get   'chat'    => 'rooms#show'

  get   'resend_validation'=> 'users#resend_validation'
  post  'resend_va' =>'users#resend_validation_action'
  get   "signup"  => "users#new", :as => "signup"
  post  "signup"  => "users#create"
  get   "order_create"  => "orders#new", :as => "order_create"
  post  "order_create"  => "orders#create"
  get   'login'   => 'sessions#new'
  post  'login'   => 'sessions#create'
  post  'addcart' => 'line_items#create'
  delete'logout'  => 'sessions#destroy'
  get   'store'   => 'store#index'
  get   'checkstock' => 'products#check_stock'
  post  'paypal'  => 'orders#process_paypal'
  get   'password_resets/new'
  get   'password_resets/edit'
  get   'stripe_checkout' => 'stripe_checkouts#stripe_checkout_session'

  mount StripeEvent::Engine, at: '/stripe_hook'
 
  resources :products, only: [:show]
  resources :messages, only: [:new, :create]
  resources :users, only: [:new, :create, :update, :edit]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :store, only: [:index]
  resource  :cart, only: [:index, :show, :destroy]
  resources :orders, only: [:new, :index, :create, :show]
  resource :payment_notification, only: [:create]


end

 









app/models/variant.rb
class Variant < ActiveRecord::Base

    extend FriendlyId
    friendly_id :SKU, slug_column: :SKU, use: [:slugged,:finders]
    include SkuGenerator.new(prefix: 'V')

	
	has_many :option_value_variants, inverse_of: :variant
	has_many :option_values, through: :option_value_variants

	has_many :line_items, inverse_of: :variant
	has_many :orders, through: :line_items
	
	has_many :variant_images, inverse_of: :variant
	has_many :images, through: :variant_images

	belongs_to :product, touch: true #, :foreign_key => 'variant_id'


	with_options presence: true do
	  validates :option_values
	  validates :SKU
	  validates :price, numericality: {greater_than_or_equal_to: 0.01}
	  #validates :cost_price, numericality: {greater_than_or_equal_to: 0.01}
	  validates :count_on_hand, numericality: {only_integer: true, greater_than_or_equal_to: 0}
	end


	def should_generate_new_friendly_id?
  		SKU_changed?
	end


   	before_save :uppercase_variant_sku

  	def uppercase_variant_sku
    	self.SKU.upcase!
  	end



end

app/controllers/admin/variants_controller.rb
class Admin::VariantsController < Admin::BaseController

	def manage
    	@product = Product.find(params[:product_id])
    end

	def edit
		@product = Product.find(params[:product_id])
		@variant = @product.variants.find(params[:id])
	end

  def update
      @product = Product.find(params[:product_id])
      @variant = @product.variants.find(params[:id])

      respond_to do |format|
        if @variant.update(variant_params)
          format.html {redirect_to edit_admin_product_variant_path(@product, @variant)
                       flash[:success] = "Successfully updated!"}
          format.json { respond_with_bip(@variant) }
        else
          format.html {redirect_to edit_admin_product_variant_url(@product, @variant), :flash => {:danger =>  @variant.errors.full_messages.join("\n") }}
          format.json { respond_with_bip(@variant) }
        end
      end
	end

  def update_active_status
    @variant = Variant.find_by(id: params[:variant][:id])
    @variant.update(active: params[:variant][:active])
    redirect_to(:back)
  end

    
private

    def variant_params
      params.require(:variant).permit(:id, :active, :hidden, :SKU, :description, :count_on_hand, :cost_price, :price, :image_ids => [])
    end


end

app/views/admin/variants/_image.html.erb
  <ul id="image_sortable" data-update-url="<%= update_variant_image_positions_admin_product_variants_url %>">
  <% image.each do |image| %>
  <li id="entry_<%=image.id%>" class="image_hover_class">
  <%= image_tag image.image_url(:product_edit).to_s %>

  <%= link_to [:admin, @product, @variant, image], method: :delete, remote: true, class: 'disable_link delete_image', title: "Delete", data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: "top" } do %>
      <i class="btn btn-danger glyphicon glyphicon-remove disable_link"></i>
    <% end %>

  </li>
  <%end%>
  </ul>

app/views/admin/variants/_new_image.html.erb
        
            <%= f.label :image, "upload images:" %>
            <%= f.file_field :image, multiple: true, name: "variants[image][]"%>


app/views/admin/variants/edit.html.erb
<% provide(:title, 'Variants') %>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" style="color: #43aef0;"><%= link_to "Product Index", admin_products_path %></li>
    <li class="breadcrumb-item" style="color: #43aef0;"><%= link_to @product.number.capitalize, edit_admin_product_path(@product) %></li>
    <li class="breadcrumb-item" style="color: #43aef0;"><%= link_to "Variant Management", admin_product_variant_management_path(@product) %></li>
    <li class="breadcrumb-item active" aria-current="page"> <%= @variant.SKU.capitalize %></li>
  </ol>
</nav>

<div class="col-lg-6">
  <div class="col-lg-12 cardboard">
    <%= render "shared/error_messages", :target => @variant %>
    <%= form_for [:admin, @product, @variant], :html => {multipart:true} do |f| %>

      <%= f.label :SKU, 'SKU' %>
      <%= f.text_field :SKU, class: "form-control" %>

      <%= f.label :count_on_hand, 'Stock' %>
      <%= number_field_tag 'variant[count_on_hand]', @variant.count_on_hand, min: 0, step: 1, class: "form-control" %>

      <%= f.label :price, 'Price (RM)' %>
      <%= f.text_field :price, class: 'form-control' %>

      <%= f.label :cost_price, 'Cost (RM)' %>
      <%= f.text_field :cost_price, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, :rows => 6, class: 'form-control' %>

      <%= f.submit "Update variant", class: "btn btn-primary btn-submit" %>
  </div>
</div>

<div class="col-lg-6">
  <div class="col-lg-12">
    <p style=" font-weight: bold; color: white; background-color: #ff8c00; padding: 5px 10px 5px 10px; margin-top:10px;"> SELECTED IMAGES </p>

    <% @variant.images.each do |image| %>
      <%= image_tag image.image_url(:product_edit).to_s, {class: 'vima'} %>
    <% end %>

    <p style=" font-weight: bold; color: white; background-color: #999999; padding: 5px 10px 5px 10px; margin-top:20px;"> IMAGE SELECTION </p>

      <% @product.images.each do |image| %>
        <%= image_tag image.image_url(:product_edit).to_s, {class: 'vima'} %>
        <%= check_box_tag 'variant[image_ids][]', image.id %>
      <% end %>

    <% end %>
  </div>
</div>


app/views/admin/variants/manage.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" style="color: #43aef0;"><%= link_to "Product Index", admin_products_path %></li>
    <li class="breadcrumb-item" style="color: #43aef0;"><%= link_to @product.number.capitalize, edit_admin_product_path(@product) %></li>
    <li class="breadcrumb-item active" aria-current="page">Variants </li>
  </ol>
</nav>

<div class="cardboard">
  <table class="table variant_table">
    <thead>
      <tr>
        <th style="width: 15%;">SKU</th>
        <th style="width: 15%;">Image</th>
        <th style="width: 20%;">Option Values</th>
        <th class="a_center" style="width: 15%;">Cost</th>
        <th class="a_center" style="width: 15%;">Price</th>
        <th class="a_center" style="width: 10%;">Quantity</th>
        <th class="a_center" style="width: 10%;">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @product.variants.each do |variant| %>
        <tr>
          <td style="color: #1d454f; font-weight: bold;"><%= link_to variant.SKU, edit_admin_product_variant_path(@product, variant) %></td>

          <td style="text-align: left;">
            <% if variant.images.any? %>
              <%= image_tag variant.images.first.image_url(:thumb) %>
            <% else %>
              <span style="background-color: #ff695a; width: 70px; color: #fff; padding: 5px; border-radius: 3px; text-align: left;"> No Image </span>
            <%end%>
          </td>

          <td><% variant.option_values.each do |vov| %> 
              <li><%= vov.name %> (<%= vov.presentation %>)</li>
              <% end %> 
          </td>

          <td class="a_center" style="font-weight: normal;" ><%= best_in_place [:admin, @product, variant], :cost_price, :display_with => :number_to_currency, :helper_options => {:unit => "RM"} %></td>
          
          <td class="a_center" style="font-weight: normal;" ><%= best_in_place [:admin, @product, variant], :price, :display_with => :number_to_currency, :helper_options => {:unit => "RM"} %></td>

          <td class="a_center" style="font-weight: normal;" ><%= best_in_place [:admin, @product, variant], :count_on_hand %></td>
          
          <td class="a_center glyph" style="width: 10%;">
            <%= link_to edit_admin_product_variant_path(@product, variant), title: "Manage", data: {toggle: 'tooltip', placement: "top" } do %>
              <i class="btn btn-success glyphicon glyphicon-book"></i>
            <% end %>
          </td>

          <% end %>
        </tr>
    </tbody>
  </table>
</div>

                
 

app/views/admin/variants/new.html.erb
<% provide(:title, 'Variants') %>

  <h1>Products</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
      <%= render "shared/error_messages", :target => @variant %>


        <%= form_for [:admin, @product, @variant], :html => {multipart:true}, url: admin_product_variant_create_path do |f| %>


          <%= f.label :count_on_hand, 'stock' %>
          <%= number_field_tag 'variant[count_on_hand]', 1, min: 1, step: 1, class:"form-control" %>

          <%= f.label :cost_price, 'cost price' %>
          <%= f.text_field :cost_price, class: 'form-control'%>

          <%= f.label :price, 'price' %>
          <%= f.text_field :price, class: 'form-control' %>
          
          <%= f.file_field :image %>

          <% @product.option_types.each do |option_type| %>
            <%= label :new_variant, option_type.presentation %>
            <%= f.collection_select 'option_value_ids', option_type.option_values, :id, :presentation,
            { include_blank: true }, { name: 'variant[option_value_ids][]', class: 'select2' } %>
          <% end %>

          <%= f.submit "Create variant", class: "btn btn-primary" %>

        <% end %>
      </div>
    </div>

app/views/admin/variants/show.html.erb
<p id="notice"><%= notice %></p>
<%= render "shared/error_messages", :target => @variant %>
<p>
  <strong>SKU:</strong>
  <%= @variant.SKU %>
</p>

<%if @variant.images.any? %>
<p>
  <strong>Image url:</strong>
  <%= image_tag @variant.images.first.image_url(:thumb) %>
</p>

<% else %>
  <p></p>
 <%end%>

<li><%= @variant.count_on_hand.to_s %></li>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@variant.price, unit: "RM") %>
</p>



<%= link_to "edit", edit_admin_product_variant_path( @product, @variant) %>



<% if false %>
<%= link_to "delete(commented)", [:admin, @product, @variant], method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


--------------------------

<% provide(:title, 'Variants') %>

    <span class="product_id_edit">Variant SKU: <%= @variant.SKU %></span>

    <span class="manage_button">
      <%= link_to admin_product_variant_management_path(@product), title: "Manage_Variant", data: {toggle: 'tooltip', placement: "top" }  do %>
        <i class="btn btn-success glyphicon glyphicon-arrow-left"></i>
      <% end %>

      <%= link_to "Back To Product", edit_admin_product_path(@product), class: "btn btn-primary" %>
    </span>

    <div class="variant_admin_page">
      <div class="col-lg-12">
      <%= render "shared/error_messages", :target => @variant %>

        <%= form_for [:admin, @product, @variant], :html => {multipart:true} do |f| %>

          <div class="col-lg-6">

            <%= f.label :SKU, 'SKU' %>
            <%= f.text_field :SKU, class: "form-control" %>

            <%= f.label :count_on_hand, 'Stock' %>
            <%= number_field_tag 'variant[count_on_hand]', @variant.count_on_hand, min: 0, step: 1, class: "form-control" %>

            <%= f.label :price, 'Price (RM)' %>
            <%= f.text_field :price, class: 'form-control' %>

            <%= f.label :cost_price, 'Cost (RM)' %>
            <%= f.text_field :cost_price, class: 'form-control' %>

            <%= f.label :description %>
            <%= f.text_area :description, :rows => 6, class: 'form-control' %>

          </div>


        <div class="col-lg-5">
          <div class="fucker2">

            <div id="variant_image">
              <% if @images.any? %>
                <%= render partial: "admin/variants/image", locals: {image: @images} %>
              <% else %>
               <p style="background-color: #90c5c7; padding: 5px 10px 5px 10px; display: inline-block; color: #fff;"> No image, upload now! </p>
              <% end %>
            </div>

            <div id="image_bar">
            </div>

          </div>

          <div class="fucker">
            <%= f.fields_for :images, @variant.images.build, :html => {multipart:true} do |builder| %>
              <%= render 'new_image', f: builder %>
            <% end %>
            <p class="image_description"> First picture will be displayed to represent product. Images can be dragged to update position.</p>
          </div>
        </div>

          <%= f.submit "Update variant", class: "btn btn-primary submit_edit_variant" %>

        <% end %>

      </div>
      </div>


  <script id="template-upload" type="text/x-tmpl">
    <div class="upload">
      <div class="progress"><div class="bar" style="width: 0%"></div></div>
    </div>
  </script>