config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  mount ActionCable.server => '/cable'

  get '/robots.:format' => 'pages#robots'
  
  namespace :admin do
    root :to => redirect('/admin/orders')

    resources :messages

    resources :orders do
      get 'manage_order' => "orders#manage_order"
      post "update_order_payment_status" => "orders#update_order_payment_status"
      post "update_order_shipment_status" => "orders#update_order_shipment_status"
      post "update_order_payment_remarks" => "orders#update_order_payment_remarks"
      post "update_order_shipment_remarks" => "orders#update_order_shipment_remarks"
      put "remove" => "orders#remove"
    end

    resources :users
    resources :products
    resources :categories, only: [:new, :index, :create, :update, :destroy]
    post "update_ot" => "product_option_types#update"
    post "update_ot_test/:product_id/:option_type_id" => "product_option_types#update_two"
    get  "deleted_index" => "orders#deleted_index"
    get  "deleted_product_index" => "products#deleted_index"
    get  "report"  => 'orders#sales_report'
    get "new_display" => 'settings#new_display'

    resources :products do
      put "remove" => "products#remove"
      put "revive" => "products#revive"
      resources :variants, only: [:show, :edit, :update] do
        resources :images
      end

      resources :images
      get "variant_management" => "variants#manage"
      get "property_management" => "products#manage_properties"
      post "update_variant_status" => "variants#update_active_status" 
      
 
      collection do
        post :update_image_positions
      end

      collection do
        post :update_properties_positions
      end
    end


   

    resources :option_types, only: [:new, :index, :create, :update, :edit] do
      resources :option_values
      collection do
        post :update_options_positions
        post :update_values_positions
      end
    end
  end

  resources :line_items do
    collection do 
      put :update_multiple
    end
  end
  
  root               'static_pages#home'
  get   'home'    => 'static_pages#home'
  get   'refund'  => 'static_pages#refund'
  get   'about'   => 'static_pages#about'
  get   'payment' => 'static_pages#pay_method'
  get   'details' => 'static_pages#about_product'
  get   'contact' => 'static_pages#contact'

  get   'chat'    => 'rooms#show'

  get   'resend_validation'=> 'users#resend_validation'
  post  'resend_va' =>'users#resend_validation_action'
  get   "signup"  => "users#new", :as => "signup"
  post  "signup"  => "users#create"
  get   "order_create"  => "orders#new", :as => "order_create"
  post  "order_create"  => "orders#create"
  get   'login'   => 'sessions#new'
  post  'login'   => 'sessions#create'
  post  'addcart' => 'line_items#create'
  delete'logout'  => 'sessions#destroy'
  get   'store'   => 'store#index'
  get   'checkstock' => 'products#check_stock'
  post  'paypal'  => 'orders#process_paypal'
  get   'password_resets/new'
  get   'password_resets/edit'
  get   'stripe_checkout' => 'stripe_checkouts#stripe_checkout_session'

  mount StripeEvent::Engine, at: '/stripe_hook'
 
  resources :products, only: [:show]
  resources :messages, only: [:new, :create]
  resources :users, only: [:new, :create, :update, :edit]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :store, only: [:index]
  resource  :cart, only: [:index, :show, :destroy]
  resources :orders, only: [:new, :index, :create, :show]
  resource :payment_notification, only: [:create]


end

 









app/models/product.rb
class Product < ActiveRecord::Base

	#include Elasticsearch::Model
  	#include Elasticsearch::Model::Callbacks

	as_enum :state, %i{discontinued available}

	before_destroy :ensure_variants_not_referenced_by_any_line_item
	after_validation :uppercase_product_number

    after_create :create_all_variants
    after_update :update_status

    validate :discontinue_date_cannot_be_in_the_past
	validates :title, :description, presence: true, uniqueness: true
	validates :option_types, presence: true

	DATE_REGEX = /((19|20)\d\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])/i

	validates :available_on, format: { with: DATE_REGEX }, :if => :available_on_changed?, allow_blank: true 
	validates :discontinue_on, format: { with: DATE_REGEX }, :if => :discontinue_on_changed?, allow_blank: true

	with_options dependent: :destroy do
		has_many :images, -> { order(:position) }
		has_many :product_option_types, inverse_of: :product
		has_many :variants
	end

	has_many :option_types, -> { order(:position) }, through: :product_option_types	
	accepts_nested_attributes_for :images, allow_destroy: true


    extend FriendlyId
    friendly_id :number, slug_column: :number, use: [:slugged,:finders]
    include NumberGenerator.new(prefix: 'P')


	def should_generate_new_friendly_id?
  		number_changed?
	end

    def find_variant(selected_option_ids)
    	 variants.includes(:option_values).select{|v| v.option_values.pluck(:id).sort! == selected_option_ids.map(&:to_i).sort! && v.option_values.size == selected_option_ids.size }.first
   	end

  	def update_status
  		if discontinue_on.present? && available_on.present?
	  		if discontinue_on >= Time.now && Date.today >= available_on
		  		update_column(:state_cd, 1)
		  	else 
		  		update_column(:state_cd, 0)
		  	end
  		else
		  	update_column(:state_cd, 0)
		end
  	end

 	private

  	def create_all_variants
		@all_array = []
		@mixed_array = []

	    option_types.each do |option_type|
	       @all_array << option_type.option_values.map(&:id)
	    end

	    @mixed_array << @all_array[0].product(*@all_array.drop(1))

	    @rep_arr = @mixed_array.flatten(1)

	    @rep_arr.each do |option_v|
	       variants.create(:count_on_hand => "5", :cost_price => "30", :price =>  "49", :option_value_ids => option_v)
	    end
    end

   	def uppercase_product_number
    	number.upcase!
    	# return nil if nothing to upcase
  	end
 
    def discontinue_date_cannot_be_in_the_past
	  	unless discontinue_on.nil? || available_on.nil? 
		    if discontinue_on <= available_on
		      errors.add(:discontinue_on, "can't be less than available date")
		    end
		end
  	end  

	 # ensure that there are no line items referencing this product (before deleted, make sure not present in any cart)
	def ensure_variants_not_referenced_by_any_line_item
	 	variants.each do |variant|
	 		if variant.line_items.empty?
	 			return true
	 		else
	 		errors.add(:base, 'Line Items present')
	 			return false
			end	
		end
	end

end

#Product.import(force: true)

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:edit, :update]
  #rescue_from ActiveRecord::RecordNotFound, with: :invalid_product
  before_action :set_option, only: [:new, :create]

  
  def index
    @search = Product.ransack(params[:q])
    @products = @search.result.where.not(hidden: true).paginate(:page => params[:page], :per_page => 10).order('updated_at DESC')
  end

  def new
    @product = Product.new
  end

  def edit
    @images=@product.images
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to edit_admin_product_url(@product)
      flash.now[:success] = "Product successfully created!"
    else
      render :new 
      flash.now[:danger] = "Unsuccessful creation, please try again!"
    end
  end

  def update
      if @product.update(product_edit_params)
        unless params[:product][:images_attributes].nil?
          params[:product][:images_attributes].each do |image|
            @image = @product.images.create(:image => image)
          end
        end
        flash[:success] = "Successfully updated!" 
        redirect_to edit_admin_product_url(@product)
      else
        redirect_to edit_admin_product_url(@product), :flash => { :danger => @product.errors.full_messages.join(', ') }
      end
  end

  def remove
    @product = Product.find(params[:product_id])
    @product.update(:hidden, true)
    
    @product.variants.each do |var|
      var.update(:count_on_hand, "0")

      Cart.all.each do |cart|
        cart.line_items.each do |line_item|
          if line_item.variant_id == var.id
            line_item.delete
          end
          cart.save!
        end
      end
    end
    redirect_to :admin_products
  end

  def revive
    @product = Product.find(params[:product_id])
    @product.update(:hidden, false)
    redirect_to :admin_products
  end

  def update_image_positions
    params[:image_entry].each_with_index do |id, index|
    Image.where(id: id).update_all(position: index + 1)
  end
    render nothing: true
  end

  def update_properties_positions
    params[:entry].each_with_index do |id, index|
    Property.where(id: id).update_all(position: index + 1)
  end
    render nothing: true
  end

  def manage_properties
    @product = Product.find(params[:product_id])
    @product.properties.build if @product.properties.empty?
  end

  def deleted_index
    @search = Product.search(params[:q])
    @products = @search.result.where.not(hidden: false).paginate(:page => params[:page], :per_page => 15).order('updated_at DESC')
  end

  private
  
    def set_product
      @product = Product.find(params[:id])
    end  

    def set_option
      @ProperOptionType = OptionType.joins(:option_values).group("option_types.id").group("option_type_id").having("count(option_values.id) >= ?",1)
    end

    def product_params
      params.require(:product).permit(:title, :description, :option_type_ids => [])
    end

    def product_edit_params
      params.require(:product).permit( :number, :state_cd, :id, :title, :description, :available_on, :discontinue_on, images_attributes:[:id, :image])
    end

    def invalid_product
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to products_url, notice: 'Invalid product'
    end

end


app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:check_stock]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_product

  def show
    @product = Product.includes(:images, :variants).friendly.find(params[:id])
    if @product.discontinued?
      flash[:danger] = "Product not available at the moment!"
      redirect_to store_url
    end
  end

  def check_stock
    unless params[:option_values].nil? 
      variant = @product.find_variant(params[:option_values])
    else
      variant = @product.variants.first
    end
    quantity = variant.count_on_hand
    description = variant.description
    price = variant.price
    respond_to do |format|
      if quantity > 0
        format.json {render json: {:quantity => quantity, :description => description, :color => "#f4bb5f", :price => price}}
      else
        format.json {render json: {:quantity => quantity, :description => description, :color => "#FF5733", :price => price}}
      end
    end
  end


  private

    def set_product
      @product = Product.friendly.find(params[:id])
    end

    def invalid_product
      logger.error "Attempt to access invalid product #{params[:id]}"
      flash[:danger] = "Error 404: Invalid Product!"
      redirect_to store_url
    end

end

app/helpers/products_helper.rb
module ProductsHelper

  def filter_option(product, options) #product object and options in an array of string
  	all_options = Hash[product.variants.map{|v| [v.id, v.option_values.ids]}] #map all product variants with Hash, key=variant.id, values=array of option value ids
  	variant_id = all_options.select{|k,v| v.sort! == options.map(&:to_i).sort! && v.size == options.size }.keys # find which variant id (key), change to array to integer and select. sort to make both position same. both must same size
  	selected_variant = Variant.find(variant_id)
  	return selected_variant[0]
  end
  
end

app/views/admin/products/_image.html.erb

<ul id="image_sortable" data-update-url="<%= update_image_positions_admin_products_url %>">
	<% image.each do |image| %>
		<li id="image_entry_<%=image.id%>" class="image_hover_class">
			<% unless image.id.nil? %>
				<%= image_tag image.image_url(:product_edit) %>	  
				<%= link_to [:admin, @product, image], method: :delete, remote: true, class: 'disable_link delete_image', title: "Delete", data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: "top" } do %>
					<i class="btn btn-danger glyphicon glyphicon-remove disable_link"></i>
				<% end %>
			<% end %>
		</li>
	<%end%>
</ul>				

app/views/admin/products/_new_image.html.erb
        
            <%= f.label :image, "upload images:" %>
            <%= f.file_field :image, multiple: true, name: "products[image][]"%>


app/views/admin/products/_property_fields.html.erb

<li id="entry_<%= f.object.id  %>" class="property_form">


    <%= f.text_field :name, class: 'form-control' %>
    <%= f.text_field :value, class: 'form-control' %>

    <%= f.hidden_field :_destroy %>
    <%= link_to "remove", '#', class: "remove_fields" %>

</li>




app/views/admin/products/deleted_index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" style="color: #43aef0;"><%= link_to "Product Index", admin_products_path %></li>
    <li class="breadcrumb-item active" aria-current="page"> Deleted Products </li>
  </ol>
</nav>


<h1 style="font-weight: bold; margin-bottom: 25px;">
  Deleted Products
</h1>

<div class="cardboard">
<table class="table product_table">
  <thead>
    <tr>
      <th style="width: 15%;">SKU</th>
      <th style="width: 15%;">Image</th>
      <th style="width: 15%; text-decoration: underline;"><%= sort_link @search, :created_at, "Date Created" %></th>
      <th style="width: 25%;">Title</th>
      <th style="width: 15%;">Status</th>
      <th style="width: 15%;">Options</th>
    </tr>
  </thead>

  <tbody>
    <%= will_paginate %>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.number.capitalize, [:edit, :admin, product] %></td>
        
        <td>
          <% if product.images.any? %>
            <%= image_tag product.images.first.image_url(:thumb) %>
          <% else %>
            <span style="background-color: #ff695a; width: 70px; color: #fff; padding: 5px; border-radius: 3px;"> No Image </span>
          <%end%>
        </td> 
        
        <td><%= product.created_at.strftime('%d %b %Y %H:%M') %></td>
        <td><%= product.title %></td>
        <td><%= product.state %></td>

        <td class="glyph">

        <%= link_to admin_product_variant_management_path(product), :method => :get, title: "Manage_Variant", data: {toggle: 'tooltip', placement: "top" } do %>
          <i class="btn btn-primary glyphicon glyphicon-duplicate"></i>
        <% end %>

        <%= link_to [:edit, :admin, product], title: "Manage", data: {toggle: 'tooltip', placement: "top" }  do %>
          <i class="btn btn-success glyphicon glyphicon-book"></i>
        <% end %>

        <%= link_to admin_product_revive_path(product), :method => :put, title: "Revive", data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: "top" } do %>
          <i class="btn btn-info glyphicon glyphicon-ok"></i>
        <% end %>


        </td>
      </tr>
    <% end %>
    <%= will_paginate %>
  </tbody>
</table>
</div>



app/views/admin/products/destroy.js.erb
$('li#entry_<%= @image.id %>').fadeOut();

app/views/admin/products/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" style="color: #43aef0;"><%= link_to "Product Index", admin_products_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @product.number.capitalize %> </li>
  </ol>
</nav>

<% provide(:title, 'Edit Products') %>

<div class="col-lg-6">
  <div class="cardboard col-lg-12">

    <p class="subtle_text"> Product ID </p>

    <h1> <%= @product.number.capitalize %> 
      <%= link_to admin_product_remove_path(@product), :method => :put, title: "Remove", data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: "top" } do %>
        <i class="btn btn-danger glyphicon glyphicon-remove"></i>
      <% end %>
    </h1>

    <br>

    <div class="subsection">
      <p class="subtle_text"> </i> Variants</p>
      <span><%= link_to "Manage", admin_product_variant_management_path(@product) %> </span>
    </div>

    <br>

    <div class="subsection">
      <p class="subtle_text"> Option Types </p>
      <ul id="option_types_sortable" data-update-url="<%= update_options_positions_admin_option_types_url %>">
        <% @product.option_types.each do |type| %>
          <li id="entry_<%=type.id%>" class="product_option_type_visibility_option">
            <span class="handle"><i class="fa fa-arrows-v"></i></span>
            <span>
              <%= type.presentation %> (<%= type.name %>)
            </span>
            <span>
            <%= react_component("react_components/Checkbox", { attribute: "#{ProductOptionType.find_by(option_type_id: type.id, product_id: @product.id).hidden}", trueValue: "false", trueName: "Visible",  falseValue: "true", falseName: "Hidden", title: "testing_only", postUrl: "/admin/update_ot_test/#{@product.id}/#{type.id}" }) %>  
            </span>
         </li>
        <% end %>
      </ul>
    </div>
  </div>


    
  <div class="cardboard col-lg-12">

    <p ><h1 style="color: #737373;"> <i class="fa fa-cog"></i> General Setup </h1></p>

    <%= render "shared/error_messages", :target => @product %>
    <%= form_for [:admin, @product], :html => {multipart:true} do |f| %>

      <%= f.label :number %>
      <%= f.text_area :number, class: 'form-control' %>

      <%= f.hidden_field :id, :value => @product.id %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, :rows => 6, class: 'form-control' %>

      <%= f.label :available_on, "Available On:" %>
      <%= f.text_field :available_on, class: 'form-control',:include_blank => true, :value => @product.available_on.try(:strftime, "%Y-%m-%d") unless f.object.new_record? %>

      <%= f.label :discontinue_on, "Discontinue On:" %>
      <%= f.text_field :discontinue_on, class: 'form-control',:include_blank => true, :value => @product.discontinue_on.try(:strftime, "%Y-%m-%d") unless f.object.new_record? %>

      <%= f.submit "Update Product", class: "btn btn-primary btn-submit" %>
  </div>
</div>




<div class="col-lg-6">
  <div class="col-lg-12">
    <div class="image_loader_top">
      <%= f.fields_for :images, @product.images.build, :html => {multipart:true} do |builder| %>
        <%= builder.label :image, "upload images:" %>
        <%= builder.file_field :image, multiple: true, name: "product[images_attributes][]"%>
      <% end %>
    </div>

    <div class="image_loader_bottom">
      <div id="toload">
        <% if @images.count > 0 %>
          <%= render partial: "admin/products/image", locals: {image: @images} %>
        <% else %>
         <p style="background-color: #90c5c7; padding: 5px 10px 5px 10px; display: inline-block; color: #fff;"> No images, upload now! </p>
        <% end %>
      </div>
      <div id="walao"></div>
    </div>
    <% end %>

  </div>
</div>


<script id="template-upload" type="text/x-tmpl">
  <div class="upload">
    <div class="progress"><div class="bar" style="width: 0%"></div></div>
  </div>
</script>


app/views/admin/products/index.html.erb


<h1 style="font-weight: bold; margin-bottom: 25px;">
  All Products <%= link_to '<i class="fa fa-plus-circle"></i>'.html_safe, new_admin_product_path, title: "New Product", data: {toggle: 'tooltip', placement: "right" } %>
</h1>

<%= will_paginate %>
<div class="clearfix"></div>

<div class="cardboard">
<table class="table product_table">
  <thead>
    <tr>
      <th style="width: 15%;">SKU</th>
      <th style="width: 15%;">Image</th>
      <th style="width: 15%; text-decoration: underline;"><%= sort_link @search, :created_at, "Date Created" %></th>
      <th style="width: 25%;">Title</th>
      <th style="width: 15%;">Status</th>
      <th style="width: 15%;">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.number.capitalize, [:edit, :admin, product] %></td>
        
        <td>
          <% if product.images.any? %>
            <%= image_tag product.images.first.image_url(:thumb) %>
          <% else %>
            <span style="background-color: #ff695a; width: 70px; color: #fff; padding: 5px; border-radius: 3px;"> No Image </span>
          <%end%>
        </td> 
        
        <td><%= product.created_at.strftime('%d %b %Y %H:%M') %></td>
        <td><%= product.title %></td>
        <td><%= product.state %></td>

        <td class="glyph">
          <%= link_to admin_product_variant_management_path(product), :method => :get, title: "Manage Variant", data: {toggle: 'tooltip', placement: "top" } do %>
            <i class="btn btn-primary glyphicon glyphicon-duplicate"></i>
          <% end %>
          <%= link_to [:edit, :admin, product], title: "Edit Product", data: {toggle: 'tooltip', placement: "top" }  do %>
            <i class="btn btn-success glyphicon glyphicon-book"></i>
          <% end %>
          <%= link_to admin_product_remove_path(product), :method => :put, title: "Remove", data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: "top" } do %>
            <i class="btn btn-danger glyphicon glyphicon-remove"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
    
  </tbody>
</table>
</div>

<%= will_paginate %>





app/views/admin/products/new.html.erb

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" style="color: #43aef0;"><%= link_to "Product Index", admin_products_path %></li>
    <li class="breadcrumb-item active" aria-current="page"> New Product </li>
  </ol>
</nav>


<% provide(:title, 'Products') %>
<div class="cardboard col-lg-6 col-lg-offset-3">
  <div class="col-lg-12">
    <div class="row">
      <%= render "shared/error_messages", :target => @product %>

        <%= form_for [:admin, @product], :html => {multipart:true} do |f| %>

          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>

          <%= f.label :description %>
          <%= f.text_area :description, :rows => 6, class: 'form-control' %>

          <%= f.label :option_type_ids %>
          <%= f.select :option_type_ids, @ProperOptionType.map { |ot| ["#{ot.presentation} (#{ot.name})", ot.id] }, {}, {:include_blank => false,  multiple: true, class: "select2"} %>

          </br>
          </br>         
          <%= f.submit "Create product", class: "btn btn-primary" %>

        <% end %>
      </div>
      </div>
  </div>




